### ISSUE TITLE
Links aren't clickable

### ISSUE THREAD

**Issue by SuperJMN** [theunrepentantgeek/Markdown.XAML#11]
I have Markdown with some links to URLs. They look clickable, but it happens nothing when the text is clicked :(

**Comment by theunrepentantgeek** [comment]
It's been a very long time since I looked at any of this code - but, from memory, clicking a link dispatches a standard WPF command (same as used for Cut/Copy/Paste, etc).

What you need to do is to provide a handler for that command, then you can do what ever you want - which can include launching a browser if you choose.

**Comment by SuperJMN** [comment]
Thanks for the quick response! I will take a look later :)

**Comment by SuperJMN** [comment]
Hello again! I've been completely unable to get this working. I've tried to intercept the `RequestNavigate` of the HyperLink objects inside the document, but they aren't raised. Can you please, create a simple example?

**Comment by SuperJMN** [comment]
OK, found the solution!

Adding this to the CommandBindings property of the Viewer (or any parent container)
```
 <FlowDocumentScrollViewer.CommandBindings>
                <CommandBinding Command="GoToPage" Executed="CommandBinding_OnExecuted"></CommandBinding>
            </FlowDocumentScrollViewer.CommandBindings>
```

And handling the command in the code-behind like this:

```
        private void CommandBinding_OnExecuted(object sender, ExecutedRoutedEventArgs e)
        {
            Process.Start((string) e.Parameter);
        }
```

**Comment by theunrepentantgeek** [comment]
Glad you worked it out. 😀
