### ISSUE TITLE
Can you create a nuget package

### ISSUE THREAD

**Issue by DerKnerd** [theunrepentantgeek/Markdown.XAML#3]
Well, the title says all. Is it possible for you to create a nuget package?

**Comment by vegardlarsen** [comment]
+1

**Comment by mglodack** [comment]
+1

**Comment by amazingant** [comment]
+1 :)

**Comment by Kryptos-FR** [comment]
-1 I don't see the point for a single class. You can copy/paste it yourself.

**Comment by fjch1997** [comment]
@Kryptos-FR 
Was gonna +1 this until I realized this is only a single class.
However, nuget is also for managing external code and updates.

**Comment by Otiel** [comment]
>I don't see the point for a single class

Be there only one class or thousands, any package manager like Nuget offers the same advantages, updates being one of them.

**Comment by txelu** [comment]
This issue should be closed as the nuget package exists now.

**Comment by theunrepentantgeek** [comment]
Reopening as I intend to create an official package to replace the one kindly created by [fmuecke](https://www.nuget.org/profiles/fmuecke) so that they don't have the burden of maintenance.

**Comment by txelu** [comment]
It would be great, because I realized that the packaged version differs from the source code in repo, though both of them are labelled as version 1.0.0. For instance `TableStyle` and `TableHeaderStyle` properties are not defined and gives an error if used with the nuget package, but they do exists on the Markdown.cs and they work correctly in the demo project.
