### ISSUE TITLE
Hyperlink not causing navigation

### ISSUE THREAD

**Issue by gep13** [theunrepentantgeek/Markdown.XAML#5]
We have been using your converter to convert Markdown from our Github Repository into our WPF application with great success, and so far it is working really well.  The only slight issue is the the rendered Hyperlink, when clicked, don't seem to do anything.  Can you please suggest what technique can be used to capture the click event of the Hyperlink and open an external browser window to navigate to the specified URL?

Thanks!

**Comment by theunrepentantgeek** [comment]
I've dug into the project that originated the Markdown converter - and it doesn't yet use hyperlinks, so there's no code I can copy as an example. There are comments in the code indicating that WPF event handling - where the events "bubble up" the visual tree - is the way to handle the links. Essentially, you'd do something at the FlowDocument level to catch the hyperlink activation.

However, I can't find details on this with a quick google, so I can't point you in the direction of an example.

What I did find was an alternative technique - selecting all the links out of the document and attaching handlers. See http://stackoverflow.com/a/10950628/30280

Hope one of those works for you.

**Comment by gep13** [comment]
@theunrepentantgeek the technique that you link to in the Stackoverflow post is something that I stumbled onto last night.  I was actually trying this last night:

https://github.com/gep13/ChocolateyGUI/commit/9456fa904f8419b4e799c167715d6ef851f6a2c3#diff-d7b827545e8b09cd3caebf0d0de04468R92

And although I can see the event handler being added in line 169:

![image](https://cloud.githubusercontent.com/assets/1271146/6234769/58c34702-b6d5-11e4-8346-6a9646b28fd8.png)

The method never actually gets called on line 176, even though the links are rendered on the UI and I am clicking on them:

![image](https://cloud.githubusercontent.com/assets/1271146/6234799/7de900b2-b6d5-11e4-8d16-e12a8d678c2a.png)

**Comment by gep13** [comment]
Hmm, I seem to have fixed it, but I honestly have no idea exactly what is going on...

If I comment out these lines, in Markdown.cs:

https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml/Markdown.cs#L110
https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml/Markdown.cs#L313
https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml/Markdown.cs#L314

Then the technique described in the Stackoverflow post that you linked to works.

Any ideas on what is going on here?

Thanks!

**Comment by theunrepentantgeek** [comment]
Hi Gary.


Good spotting - I’d forgotten about that. 


WPF has infrastructure for “commands” - for example, you can put a toolbar in place, configure buttons with the commands Cut, Copy, Paste, and everything “just works”.


Part of this is due to command-routing.


The lines of code you’ve removed are intended to integrate with this infrastructure - when the link is clicked, a “GoToPage” command is fired, with the URL included as a parameter.


If memory serves, you can handle the command by creating a CommandBinding attached to a higher level in the visual tree - the command binding triggers a regular event with the details of the command.


It would look something like this:


    <Window.CommandBindings>
        <CommandBinding 

            Command="NavigationCommands.GoToPage" 

            Executed="PerformGoToPage" 

            CanExecute="CanGoToPage" />
    </Window.CommandBindings>



Hope this is useful.

Bevan.








Sent from Windows Mail





From: Gary Ewan Park
Sent: ‎Wednesday‎, ‎18‎ ‎February‎ ‎2015 ‎10‎:‎05‎ ‎a.m.
To: theunrepentantgeek/Markdown.XAML
Cc: Bevan Arps





Hmm, I seem to have fixed it, but I honestly have no idea exactly what is going on...

If I comment out these lines, in Markdown.cs:

https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml/Markdown.cs#L110
https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml/Markdown.cs#L313
https://github.com/theunrepentantgeek/Markdown.XAML/blob/master/src/Markdown.Xaml/Markdown.cs#L314

Then the technique described in the Stackoverflow post that you linked to works.

Any ideas on what is going on here?

Thanks!

**Comment by gep13** [comment]
@theunrepentantgeek thanks so much for this tip!

This is exactly what I needed!

Just to fill this out slightly:

```
        private void CanGoToPage(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }

        private void PerformGoToPage(object sender, ExecutedRoutedEventArgs e)
        {
            Process.Start(new ProcessStartInfo(e.Parameter.ToString()));
            e.Handled = true;
        }
```

The eventhandlers for above sample code.
